repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-case-conflict #Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
    -   id: check-merge-conflict #Check for files that contain merge conflict strings.
    -   id: check-xml #Attempts to load all xml files to verify syntax.
    -   id: check-yaml #Attempts to load all yaml files to verify syntax.
    -   id: debug-statements #Check for debugger imports and py37+ breakpoint() calls in python source.
    -   id: end-of-file-fixer #Makes sure files end in a newline and only a newline.
    -   id: trailing-whitespace #Makes sure files don't have trailing-whitespaces.

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: '__init__.py$|/migrations/|.*tests\.py|manage.py'

-   repo: https://github.com/timothycrosley/isort
    rev: "5.12.0"
    hooks:
    -   id: isort
        args: [ "--profile", "black" ]
        exclude: '__init__.py$|/migrations/|.*tests\.py|manage.py'

-   repo: https://github.com/pycqa/flake8
    rev: "3.9.1"
    hooks:
    -   id: flake8
        args: [ --max-line-length=100, --config=.flake8 ]
        additional_dependencies: [ flake8-docstrings, flake8-annotations ]
        exclude: '__init__.py$|/migrations/|.*tests\.py|manage.py'

-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
    -   id: bandit
        exclude: '__init__.py$|/migrations/|.*tests\.py|manage.py'
