# Generated by Django 4.2.4 on 2023-08-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('user_type', models.CharField(choices=[('Employed', 'EMPLOYED'), ('Contractor', 'CONTRACTOR')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('On Leave', 'ON_LEAVE'), ('Terminated', 'TERMINATED')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_management_app.organization')),
            ],
        ),
    ]
