# Generated by Django 4.2.4 on 2023-08-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=200, unique=True)),
                ('subcategory', models.CharField()),
                ('warranty', models.CharField()),
                ('status', models.CharField(choices=[('Available', 'AVAILABLE'), ('In Use', 'IN_USE'), ('Maintenance', 'MAINTENANCE'), ('Lost', 'LOST'), ('Retired', 'RETIRED')], max_length=20)),
                ('primary_owner', models.CharField()),
                ('purchase_date', models.DateField()),
                ('vendor', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_management_app.users')),
            ],
        ),
    ]
