# Generated by Django 4.2.4 on 2023-11-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_app', '0002_remove_assets_warranty_assets_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='name',
            field=models.CharField(default='tset', max_length=100),
            preserve_default=False,
        ),
    ]
