# Generated by Django 4.2.4 on 2023-11-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_app', '0003_employees_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('On Leave', 'ON_LEAVE'), ('Terminated', 'TERMINATED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='user_type',
            field=models.CharField(choices=[('Employed', 'EMPLOYED'), ('Contractor', 'CONTRACTOR')], max_length=50),
        ),
    ]
